config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    get('/', {to: 'welcome#index', as: 'root'})
    get('/new', {to: 'welcome#new'})
    post('/', {to: 'welcome#create'})
    get('/destroy', {to: 'welcome#destroy'})

  resources :ideas do
    resources :reviews, only:[:create, :destroy]
    resources :likes, only:[:create, :destroy]
  
  end
  resources :users, only:[ :new, :create]
  resource :session, only:[:new, :create, :destroy]
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    can(:crud, Idea) do |idea|
      user==idea.user
     
    end

    can(:destroy, Like) do |like|
      user==like.user
    
    end
  
    can(:crud, Review )do |review|
      user==review.user
    end
    
    user ||= User.new
    
    if user.is_admin?
      can :manage,:all
    end
    


    alias_action(:Create, :read, :update, :delete, to: :crud)
  
  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    has_many :reviews, dependent: :destroy
    belongs_to :user, optional: true
    has_many :likes
    has_many :likers, through: :likes, source: :user
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :idea

    validates(
        :idea_id,
        uniqueness:{
            scope: :user_id,
            message: "you cant like more than once"
        }
    )
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :idea
    belongs_to :user ,optional: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :ideas, dependent: :nullify
    has_many :reviews, dependent: :nullify
    has_many :likes
    has_many :liked_ideas, through: :likes, source: :idea

    def full_name
        "#{first_name.capitalize} #{last_name.capitalize}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user!
        redirect_to new_session_path, notice:"Please Sign in" unless user_signed_in?
    end
    
    
    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?
    
    
    def current_user
        @current_user ||=User.find_by_id session[:user_id]
    end
    helper_method :current_user
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show ]
    before_action :find_idea, only:[:destroy, :edit]
    before_action :authorize_user!, only:[:edit,:update, :destroy]
    def index
        @idea = Idea.all
    end
    
    def new
        @idea = Idea.new
        
    end

    def create
       
        @idea = Idea.new params.require(:idea).permit(:title, :body)
        @idea.user = current_user

            if @idea.save
                flash[:notice] = "idea created successfully"
                redirect_to idea_path(@idea)
            else
                render :new
            end

               
    end

    def show
        @idea = Idea.find params[:id]
        @review = Review.new
        @reviews = @idea.reviews
      
    end

    def edit
        @idea = Idea.find params[:id]
       
    end

    def update
        @idea = Idea.find params[:id]
        if @idea.update params.require(:idea).permit(:title, :body)
            @idea.save
            redirect_to idea_path(@idea)
        else
            render :edit    
        end
    
    end

    def destroy
        @idea = Idea.find params[:id]
        authorize_user!
        if can?(:crud, @idea)
            @idea.destroy
            redirect_to '/'
         else
             head :unauthorized
         end
    end
    
    private
    def find_idea
        @idea = Idea.find params[:id]

    end
    def authorize_user!

        redirect_to root_path, alert:"Not Authorized" unless can?(:crud, @idea)
     end
end   

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        idea = Idea.find params[:idea_id]
        like = Like.new(idea: idea, user: current_user)
            if(!can?(:like, idea))
                if like.save
                    flash[:success] = "Question liked"
             
                else
                    flash[:danger] =like.errors.full_messages.join(", ")
                end
                    redirect_to root_path(idea)
            end
    end
    def destroy
        if !(can?(:destroy, like))
            like = current_user.likes.find params[:id]
            like.destroy
            redirect_to idea_path(like.idea)
        end
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    def create
        @idea = Idea.find params[:idea_id]
        @review =Review.new params.require(:review).permit(:body)
        @review.idea = @idea
        @review.user = current_user
        if @review.save
            redirect_to idea_path(@idea)
        else
            render 'ideas/show'    
    
        end
    end
    
    
    def destroy
        @review= Review.find params[:id]
        if can?(:crud,@review)
            @review.destroy
            redirect_to idea_path(@review.idea)
            else
                head :unauthorized
            end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    
    def create
        @user = User.find_by_email params[:email]
        if @user && @user.authenticate(params[:password])

            
            session[:user_id]=@user.id
            redirect_to '/', notice: "Logged in"
        else
            flash[:alert]="Wrong email or password"
            render :new
        end
    end
    
    def destroy
        session[:user_id]=nil 
        redirect_to '/', notice: "Logged Out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user=User.new
    end

    def create
        @user = User.new user_params 
        if @user.save
            session[:user_id]=@user.id
            redirect_to '/', notice: "Logged in"
        else
        render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(
            :first_name, 
            :last_name, 
            :email, 
            :password, 
            :password_confirmation
            )
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @ideas = Idea.all
        user = User.all
        @current_user = current_user
    end
    
    def new
        @idea = Idea.new
        
    end

    def create
        @idea = Idea.find params[:id]
               
    end

  


 
    def destroy
        @idea = Idea.find params[:id]
        authorize_user!
        if can?(:crud, @idea)
            @idea.destroy
            redirect_to '/'
         else
             head :unauthorized
         end
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ideas/_form.html.erb
<br>

<%= form_for @idea do |f|%>

    <div class="form-group">
    <div>
       <h2> <%= f.label :title%></h2>
        <%= f.text_field :title, size: "40x4", class: "form-control"%>
    </div>
    <br>
    <div class="form-group">
       <h2> <%= f.label :body%></h2>
        <%= f.text_area(
        :body,
        cols: 50,
        rows: 5,
        placeholder: "write post here")
        
        %>
    
    </div>
    <br>
    <%= f.submit "Create Idea", class: "btn btn-primary"%>
    </div>

<% end %>

app/views/ideas/edit.html.erb
<h1> Edit Ideas</h1>

<%= form_for @idea do |f|%>

    <div id = 'form'>
    <div>
       <h2> <%= f.label :title%></h2>
        <%= f.text_field :title, size: "40x4", class: "form-control"%>
    </div>
    <br>
    <div >
       <h2> <%= f.label :body%></h2>
        <%= f.text_area(
        :body,
        cols: 50,
        rows: 5,
        placeholder: "write post here")%>
    
    </div>
    <br>
    <%= f.submit "Edit Idea", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/ideas/index.html.erb
<div class="title-container">
<h1> Ideas</h1>

 <%= link_to 'New Post', '/ideas/new' %>
</div>

</div class="ideas">
    <% @idea.each do |idea|%>
       <div class="line">
         
            <div>
                <h3><%= link_to idea.title, idea_path(idea)%></h3>
                <p><%= idea.body%></p>
            </div>
        <div>
            <%if user_signed_in? %>
                <%= link_to(
                    "like",
                    root_path(idea),
                    method: :post
                )
                %>
         <%end%>
        </div>
        <div>
        Likes: <%=idea.likes&.count%>
        </div>
        </div>
    <% end %>
</div>

app/views/ideas/new.html.erb
<%= render "form" %>

app/views/ideas/show.html.erb
<br>
<br>
<h1><%= @idea.title %></h1>

<p><%= @idea.body %></p>
<small>
<p>Posted <%= time_ago_in_words(@idea.created_at) %> ago</p>
</small>

<% if can?(:crud, @idea)%>
    <%= link_to "Delete", idea_path(@idea), 
    method: :delete, 
    data: {confirm: "Are you sure you want to delete this idea?"}
    %>
    |
    <%= link_to "Edit", edit_idea_path(@idea)%>
<%end%>

<h2>Review:</h2>

<%= form_with(
    model: [@idea, @review], local: true) do |f| %>

    <%= f.text_area(
        :body,
        cols: 50,
        rows: 5,
        placeholder: "what's your review?"
    )%>
    <br>
    <%= f.submit "Post", class: "btn btn-primary"%>
<% end %>
<br>
<h2>Comments</h2>

<% @reviews.each do |a| %>

 <li>
        <%= a.body%>
    <br>
    <small>
           <% if can?(:crud, a)%>
        <%= link_to(
            "Delete", 
            idea_review_path(@idea, a),
            method: :delete,
            data: {
            confirm: "are you sure you want to delete this answer?"
        }
  
    )%>
     <% end %>
        <br>
    
        Reviewed <%=time_ago_in_words(a.created_at)%> ago
    </small>   
    <br>
 </li>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Idea Factory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header class="container">
        <nav class='navbar navbar-default'>
          <div class= "container-fluid">
            <div class="navbar-header">
              <%= link_to "Idea Factory", '/', class: "navbar-brand"%>
            </div>
              <ul class="nav navbar-nav navbar-right">
               <small>
                   <%if user_signed_in? %>
                      Hello, <%=current_user.full_name%>
                      |
                      <%= link_to "Sign Out", session_path,method: :delete, 
                        data: {confirm: "Are you sure you want to log out?"}  %> 
                    <% else %>
                        <%= link_to "Login", new_session_path%> |
                          |
                        <%= link_to "Sign Up", new_user_path %>   
                    <% end %> 
                </small>
              </ul>
             </div>
          </div>
          
        </nav>
        <%= yield %>
    </header>
     
  </body>
  
</html>

app/views/users/new.html.erb
<br>
<h1>Sign Up</h1>

<%= form_with model:@user, local: true do |f|  %> 
<div>
    <%=f.label :first_name  %> 
    <%= f.text_field :first_name, class: "form-control"%>
</div>
<div>
    <%= f.label :last_name  %> 
    <%= f.text_field :last_name, class: "form-control"  %> 
</div>
<div>
    <%= f.label :email  %> 
    <%= f.email_field :email, class: "form-control"  %> 
</div>

<div>
    <%= f.label :password  %> 
    <%= f.password_field :password, class: "form-control" %>
</div>
<div>
    <%= f.label :password_confirmation  %> 
    <%= f.password_field :password_confirmation, class: "form-control"%>
</div>
<br>
<%= f.submit "Sign Up", class: "btn btn-primary"%>

<% end %> 

app/views/welcome/index.html.erb
<div class="title-container">
<h1> Ideas</h1>

 <%= link_to 'New Idea', '/ideas/new' %>
</div>
    
</div class="ideas">
    <% @ideas.each do |idea|%>
       <div class="line">
         
            <div>
                <h3><%= link_to idea.title, idea_path(idea)%></h3>
                <p><%= idea.body%></p>
            </div>

             <div>
                 <small> by
                 
                 <% user = User.all%>
                 <% find = user.find(idea.user_id)%> 
                 <%= find.first_name%>

                    <%if user_signed_in? %>
                    |
                        <%= link_to( 
                            "Like", 
                            idea_like_path(idea),
                            method: :post
                            )   
                    %>
                   
                
                   
                    |
                     <% if idea.likes.find_by(user: @current_user)%>
                        <%= link_to( 
                            "Un-like", 
                            root_path(idea),
                            method: :delete
                            )   
                        %>
                    <%end%>
                     <%end%>
                 </small>
             </div>
           
            <div>
                Likes: <%=idea.likes&.count%>
            </div>
            
        </div>
    <% end %>
</div>